[package]
name = "motorkit"
version = "0.1.0"
authors = ["telastrus <10052313+telastrus@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal="0.11"